//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace HlidacStatu.Lib.XSD {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.gov.cz/rejstriky/ISRS/1.2/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://portal.gov.cz/rejstriky/ISRS/1.2/", IsNullable=false)]
    public partial class dump {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string mesic;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string rok;
        
        /// <remarks/>
        public System.DateTime casGenerovani;
        
        /// <remarks/>
        public bool dokoncenyMesic;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("zaznam")]
        public dumpZaznam[] zaznam;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.gov.cz/rejstriky/ISRS/1.2/")]
    public partial class dumpZaznam {

        public string Id
        {
            get
            {
                return this.identifikator.idVerze;
            }
        }

        /// <remarks/>
        public tIdentifikator identifikator;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string odkaz;
        
        /// <remarks/>
        public System.DateTime casZverejneni;
        
        /// <remarks/>
        public tSmlouva smlouva;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("priloha", IsNullable=false)]
        public tPrilohaOdkaz[] prilohy;
        
        /// <remarks/>
        public bool platnyZaznam;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.gov.cz/rejstriky/ISRS/1.2/")]
    public partial class tIdentifikator {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string idSmlouvy;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string idVerze;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.gov.cz/rejstriky/ISRS/1.2/")]
    public partial class tHash {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string algoritmus;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.gov.cz/rejstriky/ISRS/1.2/")]
    public partial class tPrilohaOdkaz {

        public byte[] data;
        /// <remarks/>
        public string nazevSouboru;
        
        /// <remarks/>
        public tHash hash;
        
        /// <remarks/>
        public string odkaz;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.gov.cz/rejstriky/ISRS/1.2/")]
    public partial class tSmlouva {
        
        /// <remarks/>
        public tSmlouvaSubjekt subjekt;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("smluvniStrana")]
        public tSmlouvaSmluvniStrana[] smluvniStrana;
        
        /// <remarks/>
        public string predmet;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime datumUzavreni;
        
        /// <remarks/>
        public string cisloSmlouvy;
        
        /// <remarks/>
        public string schvalil;
        
        /// <remarks/>
        public decimal hodnotaBezDph;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hodnotaBezDphSpecified;
        
        /// <remarks/>
        public decimal hodnotaVcetneDph;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hodnotaVcetneDphSpecified;
        
        /// <remarks/>
        public tSmlouvaCiziMena ciziMena;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string navazanyZaznam;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.gov.cz/rejstriky/ISRS/1.2/")]
    public partial class tSmlouvaSubjekt {
        
        /// <remarks/>
        public string datovaSchranka;
        
        /// <remarks/>
        public string nazev;
        
        /// <remarks/>
        public string ico;
        
        /// <remarks/>
        public string adresa;
        
        /// <remarks/>
        public string utvar;
        
        /// <remarks/>
        public bool? platce;
        
        ///// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool platceSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.gov.cz/rejstriky/ISRS/1.2/")]
    public partial class tSmlouvaSmluvniStrana {
        
        /// <remarks/>
        public string datovaSchranka;
        
        /// <remarks/>
        public string nazev;
        
        /// <remarks/>
        public string ico;
        
        /// <remarks/>
        public string adresa;
        
        /// <remarks/>
        public string utvar;
        
        /// <remarks/>
        public bool? prijemce;
        
        ///// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool prijemceSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.gov.cz/rejstriky/ISRS/1.2/")]
    public partial class tSmlouvaCiziMena {
        
        /// <remarks/>
        public decimal hodnota;
        
        /// <remarks/>
        public string mena;
    }
}
