//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace HlidacStatu.Lib.XSD {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.gov.cz/rejstriky/ISRS/1.2/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://portal.gov.cz/rejstriky/ISRS/1.2/", IsNullable=false)]
    public partial class daily {

        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string den = "0";
       
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string mesic;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string rok;
        
        /// <remarks/>
        public System.DateTime casGenerovani;
        
        /// <remarks/>
        public bool dokoncenyMesic = true;

        /// <remarks/>
        public bool dokoncenyDen = true;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("zaznam")]
        public dumpZaznam[] zaznam;

        public dump ToDump()
        {
            dump d = new dump();
            d.den = this.den;
            d.mesic = this.mesic;
            d.rok = this.rok;
            d.casGenerovani = this.casGenerovani;
            d.dokoncenyDen = this.dokoncenyDen;
            d.dokoncenyMesic = this.dokoncenyMesic;
            d.zaznam = this.zaznam;

            return d;
        
        }
    }
  
}
