//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HlidacStatu.Lib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUserToken
    {
        public string Id { get; set; }
        public System.Guid Token { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> LastAccess { get; set; }
        public int Count { get; set; }
    }
}
