//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HlidacStatu.Lib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int pk { get; set; }
        public System.DateTime date { get; set; }
        public string userId { get; set; }
        public string operation { get; set; }
        public string objectType { get; set; }
        public string objectId { get; set; }
        public string valueBefore { get; set; }
        public string valueAfter { get; set; }
        public string IP { get; set; }
    }
}
