//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HlidacStatu.Lib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookmark
    {
        public System.Guid Id { get; set; }
        public string UserId { get; set; }
        public string Folder { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public int ItemType { get; set; }
        public string ItemId { get; set; }
        public System.DateTime Created { get; set; }
    }
}
