//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HlidacStatu.Lib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassificationOverride
    {
        public int Id { get; set; }
        public string IdSmlouvy { get; set; }
        public Nullable<int> OriginalCat1 { get; set; }
        public Nullable<int> OriginalCat2 { get; set; }
        public Nullable<int> CorrectCat1 { get; set; }
        public Nullable<int> CorrectCat2 { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
