//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HlidacStatu.Lib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatoveSchranky
    {
        public string DS { get; set; }
        public string Identifikator { get; set; }
        public string DetailJson { get; set; }
        public string Url { get; set; }
    }
}
