//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HlidacStatu.Lib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventSubType
    {
        public int Id { get; set; }
        public Nullable<int> EventTypeId { get; set; }
        public string NameMale { get; set; }
        public string NameFemale { get; set; }
    }
}
