//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HlidacStatu.Lib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceItems
    {
        public int ID { get; set; }
        public int ID_Invoice { get; set; }
        public string Name { get; set; }
        public Nullable<int> ID_ShopItem { get; set; }
        public int Amount { get; set; }
        public decimal Price { get; set; }
        public decimal Discount { get; set; }
        public Nullable<System.DateTime> Expires { get; set; }
        public System.DateTime Created { get; set; }
        public decimal VAT { get; set; }
    
        public virtual Invoices Invoices { get; set; }
    }
}
