//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HlidacStatu.Lib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemToOcrQueue
    {
        public int pk { get; set; }
        public string itemType { get; set; }
        public string itemSubType { get; set; }
        public string itemId { get; set; }
        public System.DateTime created { get; set; }
        public Nullable<System.DateTime> done { get; set; }
        public string result { get; set; }
        public Nullable<System.DateTime> started { get; set; }
        public Nullable<int> success { get; set; }
        public Nullable<int> priority { get; set; }
    }
}
