//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HlidacStatu.Lib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public string ICO { get; set; }
        public string DIC { get; set; }
        public string Jmeno { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> PaidUntil { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string UserId { get; set; }
    }
}
