//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HlidacStatu.Lib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OsobaVazby
    {
        public int pk { get; set; }
        public int OsobaID { get; set; }
        public string VazbakICO { get; set; }
        public Nullable<int> TypVazby { get; set; }
        public string PojmenovaniVazby { get; set; }
        public Nullable<decimal> podil { get; set; }
        public string Zdroj { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public Nullable<System.DateTime> DatumOd { get; set; }
        public Nullable<System.DateTime> DatumDo { get; set; }
        public Nullable<int> VazbakOsobaId { get; set; }
        public Nullable<int> RucniZapis { get; set; }
        public string Poznamka { get; set; }
    }
}
