//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HlidacStatu.Lib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OsobaEvent
    {
        public int pk { get; set; }
        public int OsobaId { get; set; }
        public string Title { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DatumOd { get; set; }
        public Nullable<System.DateTime> DatumDo { get; set; }
        public int Type { get; set; }
        public string AddInfo { get; set; }
        public Nullable<decimal> AddInfoNum { get; set; }
        public System.DateTime Created { get; set; }
        public string Zdroj { get; set; }
        public string Organizace { get; set; }
    }
}
