//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HlidacStatu.Lib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmlouvyId
    {
        public string Id { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime updated { get; set; }
        public int active { get; set; }
    }
}
