//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HlidacStatu.Lib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UcetniJednotka
    {
        public string ico { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string ucjed_nazev { get; set; }
        public string dic { get; set; }
        public string adresa { get; set; }
        public string nuts_id { get; set; }
        public string zrizovatel_ico { get; set; }
        public Nullable<int> cofog_id { get; set; }
        public Nullable<int> isektor_id { get; set; }
        public Nullable<int> kapitola_id { get; set; }
        public Nullable<int> nace_id { get; set; }
        public Nullable<int> druhuj_id { get; set; }
        public Nullable<int> poddruhuj_id { get; set; }
        public Nullable<System.DateTime> konecplat { get; set; }
        public Nullable<int> forma_id { get; set; }
        public Nullable<int> katobyv_id { get; set; }
        public string obec { get; set; }
        public string kraj { get; set; }
        public Nullable<int> stat_id { get; set; }
        public Nullable<int> zdrojfin_id { get; set; }
        public Nullable<int> druhrizeni_id { get; set; }
        public Nullable<int> veduc_id { get; set; }
        public string zuj { get; set; }
        public string sidlo { get; set; }
        public Nullable<int> zpodm_id { get; set; }
        public Nullable<int> kod_pou { get; set; }
        public Nullable<int> typorg_id { get; set; }
        public Nullable<int> pocob { get; set; }
        public string ulice { get; set; }
        public Nullable<int> kod_rp { get; set; }
        public Nullable<System.DateTime> datumakt { get; set; }
        public Nullable<int> aktorg_id { get; set; }
        public Nullable<System.DateTime> datumvzniku { get; set; }
        public string psc { get; set; }
    }
}
