/*
 * REST API Hlídače státu
 *
 * REST API Hlídače státu
 *
 * OpenAPI spec version: 2.0.0
 * Contact: podpora@hlidacstatu.cz
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace HlidacStatu.Web.Models.Apiv2
{ 
    /// <summary>
    /// je nenullové, pokud je cena určena v cizí měně
    /// </summary>
    [DataContract]
    public partial class SmlouvaCiziMena : IEquatable<SmlouvaCiziMena>
    { 
        /// <summary>
        /// Gets or Sets Hodnota
        /// </summary>
        [Required]
        [DataMember(Name="hodnota")]
        public decimal? Hodnota { get; set; }

        /// <summary>
        /// např. EUR
        /// </summary>
        /// <value>např. EUR</value>
        [Required]
        [DataMember(Name="mena")]
        public string Mena { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SmlouvaCiziMena {\n");
            sb.Append("  Hodnota: ").Append(Hodnota).Append("\n");
            sb.Append("  Mena: ").Append(Mena).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SmlouvaCiziMena)obj);
        }

        /// <summary>
        /// Returns true if SmlouvaCiziMena instances are equal
        /// </summary>
        /// <param name="other">Instance of SmlouvaCiziMena to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SmlouvaCiziMena other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Hodnota == other.Hodnota ||
                    Hodnota != null &&
                    Hodnota.Equals(other.Hodnota)
                ) && 
                (
                    Mena == other.Mena ||
                    Mena != null &&
                    Mena.Equals(other.Mena)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Hodnota != null)
                    hashCode = hashCode * 59 + Hodnota.GetHashCode();
                    if (Mena != null)
                    hashCode = hashCode * 59 + Mena.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SmlouvaCiziMena left, SmlouvaCiziMena right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SmlouvaCiziMena left, SmlouvaCiziMena right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
