/*
 * REST API Hlídače státu
 *
 * REST API Hlídače státu
 *
 * OpenAPI spec version: 2.0.0
 * Contact: podpora@hlidacstatu.cz
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace HlidacStatu.Web.Models.Apiv2
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class VerejnaZakazkaZadavatel : IEquatable<VerejnaZakazkaZadavatel>
    { 
        /// <summary>
        /// IČO zadavatele
        /// </summary>
        /// <value>IČO zadavatele</value>
        [Required]
        [DataMember(Name="iCO")]
        public string ICO { get; set; }

        /// <summary>
        /// Název subjektu zadavatele
        /// </summary>
        /// <value>Název subjektu zadavatele</value>
        [Required]
        [DataMember(Name="jmeno")]
        public string Jmeno { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VerejnaZakazkaZadavatel {\n");
            sb.Append("  ICO: ").Append(ICO).Append("\n");
            sb.Append("  Jmeno: ").Append(Jmeno).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((VerejnaZakazkaZadavatel)obj);
        }

        /// <summary>
        /// Returns true if VerejnaZakazkaZadavatel instances are equal
        /// </summary>
        /// <param name="other">Instance of VerejnaZakazkaZadavatel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VerejnaZakazkaZadavatel other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ICO == other.ICO ||
                    ICO != null &&
                    ICO.Equals(other.ICO)
                ) && 
                (
                    Jmeno == other.Jmeno ||
                    Jmeno != null &&
                    Jmeno.Equals(other.Jmeno)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ICO != null)
                    hashCode = hashCode * 59 + ICO.GetHashCode();
                    if (Jmeno != null)
                    hashCode = hashCode * 59 + Jmeno.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(VerejnaZakazkaZadavatel left, VerejnaZakazkaZadavatel right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(VerejnaZakazkaZadavatel left, VerejnaZakazkaZadavatel right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
