//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HlidacStatu.Lib.Db.Insolvence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokumenty
    {
        public string RizeniId { get; set; }
        public int TypUdalosti { get; set; }
        public System.DateTime DatumVlozeni { get; set; }
        public string Popis { get; set; }
        public string Url { get; set; }
        public string Oddil { get; set; }
        public int Length { get; set; }
        public int WordCount { get; set; }
        public int pk { get; set; }
        public string DokumentId { get; set; }
    }
}
