//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HlidacStatu.Lib.Db.Insolvence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rizeni
    {
        public string SpisovaZnacka { get; set; }
        public string Stav { get; set; }
        public System.DateTime DatumZalozeni { get; set; }
        public System.DateTime PosledniZmena { get; set; }
        public string Soud { get; set; }
        public bool OnRadar { get; set; }
    }
}
