//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSDL_tester.PUB01A {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class Error : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorDescriptionField;
        
        private System.DateTime dateTimeField;
        
        private string sIDField;
        
        private string requestIDField;
        
        private SRVid sRVidField;
        
        private string vOKOidField;
        
        private string responseLangField;
        
        private string showXSLTpathField;
        
        private string showXSLTtypeField;
        
        private string displayField;
        
        private string descField;
        
        private System.Xml.XmlElement innerExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("ErrorDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
                this.RaisePropertyChanged("DateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SID {
            get {
                return this.sIDField;
            }
            set {
                this.sIDField = value;
                this.RaisePropertyChanged("SID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
                this.RaisePropertyChanged("RequestID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public SRVid SRVid {
            get {
                return this.sRVidField;
            }
            set {
                this.sRVidField = value;
                this.RaisePropertyChanged("SRVid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string vOKOid {
            get {
                return this.vOKOidField;
            }
            set {
                this.vOKOidField = value;
                this.RaisePropertyChanged("vOKOid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ResponseLang {
            get {
                return this.responseLangField;
            }
            set {
                this.responseLangField = value;
                this.RaisePropertyChanged("ResponseLang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ShowXSLTpath {
            get {
                return this.showXSLTpathField;
            }
            set {
                this.showXSLTpathField = value;
                this.RaisePropertyChanged("ShowXSLTpath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ShowXSLTtype {
            get {
                return this.showXSLTtypeField;
            }
            set {
                this.showXSLTtypeField = value;
                this.RaisePropertyChanged("ShowXSLTtype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Display {
            get {
                return this.displayField;
            }
            set {
                this.displayField = value;
                this.RaisePropertyChanged("Display");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("Desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.Xml.XmlElement InnerException {
            get {
                return this.innerExceptionField;
            }
            set {
                this.innerExceptionField = value;
                this.RaisePropertyChanged("InnerException");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class SRVid : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serverIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string serverID {
            get {
                return this.serverIDField;
            }
            set {
                this.serverIDField = value;
                this.RaisePropertyChanged("serverID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RdmServices/RDM_PUB01A")]
    public partial class narizeni_stav : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime platnostField;
        
        private bool platnostFieldSpecified;
        
        private string kodField;
        
        private double limitField;
        
        private double cerpanoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime platnost {
            get {
                return this.platnostField;
            }
            set {
                this.platnostField = value;
                this.RaisePropertyChanged("platnost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool platnostSpecified {
            get {
                return this.platnostFieldSpecified;
            }
            set {
                this.platnostFieldSpecified = value;
                this.RaisePropertyChanged("platnostSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string kod {
            get {
                return this.kodField;
            }
            set {
                this.kodField = value;
                this.RaisePropertyChanged("kod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
                this.RaisePropertyChanged("limit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double cerpano {
            get {
                return this.cerpanoField;
            }
            set {
                this.cerpanoField = value;
                this.RaisePropertyChanged("cerpano");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RdmServices/RDM_PUB01A")]
    public partial class oblast_stav : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime platnostField;
        
        private string oblast_kodField;
        
        private double limitField;
        
        private double cerpanoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime platnost {
            get {
                return this.platnostField;
            }
            set {
                this.platnostField = value;
                this.RaisePropertyChanged("platnost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string oblast_kod {
            get {
                return this.oblast_kodField;
            }
            set {
                this.oblast_kodField = value;
                this.RaisePropertyChanged("oblast_kod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
                this.RaisePropertyChanged("limit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double cerpano {
            get {
                return this.cerpanoField;
            }
            set {
                this.cerpanoField = value;
                this.RaisePropertyChanged("cerpano");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RdmServices/RDM_PUB01A")]
    public partial class adresa_type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ulicenazField;
        
        private string cisdomhodField;
        
        private string cisorhodField;
        
        private string cisorpisField;
        
        private string cobcenazField;
        
        private string mcastnazField;
        
        private string obecnazField;
        
        private string pscField;
        
        private string adrline1Field;
        
        private string adrline2Field;
        
        private string adrline3Field;
        
        private string adrline4Field;
        
        private string adrpostcodeField;
        
        private string kodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ulicenaz {
            get {
                return this.ulicenazField;
            }
            set {
                this.ulicenazField = value;
                this.RaisePropertyChanged("ulicenaz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cisdomhod {
            get {
                return this.cisdomhodField;
            }
            set {
                this.cisdomhodField = value;
                this.RaisePropertyChanged("cisdomhod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string cisorhod {
            get {
                return this.cisorhodField;
            }
            set {
                this.cisorhodField = value;
                this.RaisePropertyChanged("cisorhod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string cisorpis {
            get {
                return this.cisorpisField;
            }
            set {
                this.cisorpisField = value;
                this.RaisePropertyChanged("cisorpis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string cobcenaz {
            get {
                return this.cobcenazField;
            }
            set {
                this.cobcenazField = value;
                this.RaisePropertyChanged("cobcenaz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string mcastnaz {
            get {
                return this.mcastnazField;
            }
            set {
                this.mcastnazField = value;
                this.RaisePropertyChanged("mcastnaz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string obecnaz {
            get {
                return this.obecnazField;
            }
            set {
                this.obecnazField = value;
                this.RaisePropertyChanged("obecnaz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string psc {
            get {
                return this.pscField;
            }
            set {
                this.pscField = value;
                this.RaisePropertyChanged("psc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string adrline1 {
            get {
                return this.adrline1Field;
            }
            set {
                this.adrline1Field = value;
                this.RaisePropertyChanged("adrline1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string adrline2 {
            get {
                return this.adrline2Field;
            }
            set {
                this.adrline2Field = value;
                this.RaisePropertyChanged("adrline2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string adrline3 {
            get {
                return this.adrline3Field;
            }
            set {
                this.adrline3Field = value;
                this.RaisePropertyChanged("adrline3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string adrline4 {
            get {
                return this.adrline4Field;
            }
            set {
                this.adrline4Field = value;
                this.RaisePropertyChanged("adrline4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string adrpostcode {
            get {
                return this.adrpostcodeField;
            }
            set {
                this.adrpostcodeField = value;
                this.RaisePropertyChanged("adrpostcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=13)]
        public string kod {
            get {
                return this.kodField;
            }
            set {
                this.kodField = value;
                this.RaisePropertyChanged("kod");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RdmServices/RDM_PUB01A")]
    public partial class identifikator_type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typField;
        
        private System.DateTime platnostdoField;
        
        private bool platnostdoFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string typ {
            get {
                return this.typField;
            }
            set {
                this.typField = value;
                this.RaisePropertyChanged("typ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime platnostdo {
            get {
                return this.platnostdoField;
            }
            set {
                this.platnostdoField = value;
                this.RaisePropertyChanged("platnostdo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool platnostdoSpecified {
            get {
                return this.platnostdoFieldSpecified;
            }
            set {
                this.platnostdoFieldSpecified = value;
                this.RaisePropertyChanged("platnostdoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RdmServices/RDM_PUB01A")]
    public partial class subjekt_type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string subjektidField;
        
        private string obchodni_jmenoField;
        
        private string jmenoField;
        
        private string prijmeniField;
        
        private identifikator_type[] seznam_identifikatoruField;
        
        private adresa_type adresaField;
        
        private oblast_stav[] limity_stavField;
        
        private narizeni_stav[] limity_stav_narizeniField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=0)]
        public string subjektid {
            get {
                return this.subjektidField;
            }
            set {
                this.subjektidField = value;
                this.RaisePropertyChanged("subjektid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string obchodni_jmeno {
            get {
                return this.obchodni_jmenoField;
            }
            set {
                this.obchodni_jmenoField = value;
                this.RaisePropertyChanged("obchodni_jmeno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string jmeno {
            get {
                return this.jmenoField;
            }
            set {
                this.jmenoField = value;
                this.RaisePropertyChanged("jmeno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string prijmeni {
            get {
                return this.prijmeniField;
            }
            set {
                this.prijmeniField = value;
                this.RaisePropertyChanged("prijmeni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("identifikator")]
        public identifikator_type[] seznam_identifikatoru {
            get {
                return this.seznam_identifikatoruField;
            }
            set {
                this.seznam_identifikatoruField = value;
                this.RaisePropertyChanged("seznam_identifikatoru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public adresa_type adresa {
            get {
                return this.adresaField;
            }
            set {
                this.adresaField = value;
                this.RaisePropertyChanged("adresa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public oblast_stav[] limity_stav {
            get {
                return this.limity_stavField;
            }
            set {
                this.limity_stavField = value;
                this.RaisePropertyChanged("limity_stav");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public narizeni_stav[] limity_stav_narizeni {
            get {
                return this.limity_stav_narizeniField;
            }
            set {
                this.limity_stav_narizeniField = value;
                this.RaisePropertyChanged("limity_stav_narizeni");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Response", Namespace="http://www.pds.eu/RdmServices/RDM_PUB01A")]
    public partial class Response1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int pocetField;
        
        private subjekt_type[] seznam_subjektuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int pocet {
            get {
                return this.pocetField;
            }
            set {
                this.pocetField = value;
                this.RaisePropertyChanged("pocet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("subjekt")]
        public subjekt_type[] seznam_subjektu {
            get {
                return this.seznam_subjektuField;
            }
            set {
                this.seznam_subjektuField = value;
                this.RaisePropertyChanged("seznam_subjektu");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class ResponseHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
                this.RaisePropertyChanged("RequestID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SRVid sRVidField;
        
        private TimeStamp timeStampField;
        
        private ResponseHeader responseHeaderField;
        
        private ResponseResponseContent responseContentField;
        
        private string vOKOidField;
        
        private string sIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SRVid SRVid {
            get {
                return this.sRVidField;
            }
            set {
                this.sRVidField = value;
                this.RaisePropertyChanged("SRVid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TimeStamp TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ResponseHeader ResponseHeader {
            get {
                return this.responseHeaderField;
            }
            set {
                this.responseHeaderField = value;
                this.RaisePropertyChanged("ResponseHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ResponseResponseContent ResponseContent {
            get {
                return this.responseContentField;
            }
            set {
                this.responseContentField = value;
                this.RaisePropertyChanged("ResponseContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string vOKOid {
            get {
                return this.vOKOidField;
            }
            set {
                this.vOKOidField = value;
                this.RaisePropertyChanged("vOKOid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SID {
            get {
                return this.sIDField;
            }
            set {
                this.sIDField = value;
                this.RaisePropertyChanged("SID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class TimeStamp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TimeStampType typeField;
        
        private System.DateTime valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TimeStampType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public System.DateTime Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.pds.eu/vOKO/v0200")]
    public enum TimeStampType {
        
        /// <remarks/>
        @base,
        
        /// <remarks/>
        qualified,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class ResponseResponseContent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Response1 itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Response", Namespace="http://www.pds.eu/RdmServices/RDM_PUB01A", Order=0)]
        public Response1 Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RdmServices/RDM_PUB01A")]
    public partial class dotaz_type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string icField;
        
        private string subjektidField;
        
        private string jmenoField;
        
        private string prijmeniField;
        
        private string obecnazField;
        
        private string pscField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ic {
            get {
                return this.icField;
            }
            set {
                this.icField = value;
                this.RaisePropertyChanged("ic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=1)]
        public string subjektid {
            get {
                return this.subjektidField;
            }
            set {
                this.subjektidField = value;
                this.RaisePropertyChanged("subjektid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string jmeno {
            get {
                return this.jmenoField;
            }
            set {
                this.jmenoField = value;
                this.RaisePropertyChanged("jmeno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string prijmeni {
            get {
                return this.prijmeniField;
            }
            set {
                this.prijmeniField = value;
                this.RaisePropertyChanged("prijmeni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string obecnaz {
            get {
                return this.obecnazField;
            }
            set {
                this.obecnazField = value;
                this.RaisePropertyChanged("obecnaz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string psc {
            get {
                return this.pscField;
            }
            set {
                this.pscField = value;
                this.RaisePropertyChanged("psc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RdmServices/RDM_PUB01A")]
    public partial class RDM_PUB_Request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private dotaz_type dotazField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public dotaz_type dotaz {
            get {
                return this.dotazField;
            }
            set {
                this.dotazField = value;
                this.RaisePropertyChanged("dotaz");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class RequestHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestIDField;
        
        private RequestHeaderSubject subjectField;
        
        private RequestHeaderRequestType requestTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
                this.RaisePropertyChanged("RequestID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RequestHeaderSubject Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("Subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RequestHeaderRequestType RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
                this.RaisePropertyChanged("RequestType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class RequestHeaderSubject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string subjectIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string subjectID {
            get {
                return this.subjectIDField;
            }
            set {
                this.subjectIDField = value;
                this.RaisePropertyChanged("subjectID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class RequestHeaderRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class AppInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AppInfoAppModule appModuleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AppInfoAppModule AppModule {
            get {
                return this.appModuleField;
            }
            set {
                this.appModuleField = value;
                this.RaisePropertyChanged("AppModule");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class AppInfoAppModule : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class UIDkey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dnField;
        
        private string addressADField;
        
        private string certificateSNField;
        
        private string certificateOwnerField;
        
        private string certificateOrganizationField;
        
        private string certificateIssuerField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dn {
            get {
                return this.dnField;
            }
            set {
                this.dnField = value;
                this.RaisePropertyChanged("dn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string addressAD {
            get {
                return this.addressADField;
            }
            set {
                this.addressADField = value;
                this.RaisePropertyChanged("addressAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string certificateSN {
            get {
                return this.certificateSNField;
            }
            set {
                this.certificateSNField = value;
                this.RaisePropertyChanged("certificateSN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string certificateOwner {
            get {
                return this.certificateOwnerField;
            }
            set {
                this.certificateOwnerField = value;
                this.RaisePropertyChanged("certificateOwner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string certificateOrganization {
            get {
                return this.certificateOrganizationField;
            }
            set {
                this.certificateOrganizationField = value;
                this.RaisePropertyChanged("certificateOrganization");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string certificateIssuer {
            get {
                return this.certificateIssuerField;
            }
            set {
                this.certificateIssuerField = value;
                this.RaisePropertyChanged("certificateIssuer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class Request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private UIDkey uIDkeyField;
        
        private TimeStamp timeStampField;
        
        private AppInfo appInfoField;
        
        private RequestHeader requestHeaderField;
        
        private RequestRequestContent requestContentField;
        
        private string vOKOidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public UIDkey UIDkey {
            get {
                return this.uIDkeyField;
            }
            set {
                this.uIDkeyField = value;
                this.RaisePropertyChanged("UIDkey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TimeStamp TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public AppInfo AppInfo {
            get {
                return this.appInfoField;
            }
            set {
                this.appInfoField = value;
                this.RaisePropertyChanged("AppInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public RequestHeader RequestHeader {
            get {
                return this.requestHeaderField;
            }
            set {
                this.requestHeaderField = value;
                this.RaisePropertyChanged("RequestHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public RequestRequestContent RequestContent {
            get {
                return this.requestContentField;
            }
            set {
                this.requestContentField = value;
                this.RaisePropertyChanged("RequestContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string vOKOid {
            get {
                return this.vOKOidField;
            }
            set {
                this.vOKOidField = value;
                this.RaisePropertyChanged("vOKOid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class RequestRequestContent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RDM_PUB_Request itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Request", Namespace="http://www.pds.eu/RdmServices/RDM_PUB01A", Order=0)]
        public RDM_PUB_Request Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.pds.eu/vOKO/v0200", ConfigurationName="PUB01A.RDM_PUB01A")]
    public interface RDM_PUB01A {
        
        // CODEGEN: Generating message contract since the operation process is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="process", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WSDL_tester.PUB01A.Error), Action="process", Name="Error")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WSDL_tester.PUB01A.processResponse process(WSDL_tester.PUB01A.processRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="process", ReplyAction="*")]
        System.Threading.Tasks.Task<WSDL_tester.PUB01A.processResponse> processAsync(WSDL_tester.PUB01A.processRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.pds.eu/vOKO/v0200", Order=0)]
        public WSDL_tester.PUB01A.Request Request;
        
        public processRequest() {
        }
        
        public processRequest(WSDL_tester.PUB01A.Request Request) {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.pds.eu/vOKO/v0200", Order=0)]
        public WSDL_tester.PUB01A.Response Response;
        
        public processResponse() {
        }
        
        public processResponse(WSDL_tester.PUB01A.Response Response) {
            this.Response = Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RDM_PUB01AChannel : WSDL_tester.PUB01A.RDM_PUB01A, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RDM_PUB01AClient : System.ServiceModel.ClientBase<WSDL_tester.PUB01A.RDM_PUB01A>, WSDL_tester.PUB01A.RDM_PUB01A {
        
        public RDM_PUB01AClient() {
        }
        
        public RDM_PUB01AClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RDM_PUB01AClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RDM_PUB01AClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RDM_PUB01AClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSDL_tester.PUB01A.processResponse WSDL_tester.PUB01A.RDM_PUB01A.process(WSDL_tester.PUB01A.processRequest request) {
            return base.Channel.process(request);
        }
        
        public WSDL_tester.PUB01A.Response process(WSDL_tester.PUB01A.Request Request) {
            WSDL_tester.PUB01A.processRequest inValue = new WSDL_tester.PUB01A.processRequest();
            inValue.Request = Request;
            WSDL_tester.PUB01A.processResponse retVal = ((WSDL_tester.PUB01A.RDM_PUB01A)(this)).process(inValue);
            return retVal.Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSDL_tester.PUB01A.processResponse> WSDL_tester.PUB01A.RDM_PUB01A.processAsync(WSDL_tester.PUB01A.processRequest request) {
            return base.Channel.processAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSDL_tester.PUB01A.processResponse> processAsync(WSDL_tester.PUB01A.Request Request) {
            WSDL_tester.PUB01A.processRequest inValue = new WSDL_tester.PUB01A.processRequest();
            inValue.Request = Request;
            return ((WSDL_tester.PUB01A.RDM_PUB01A)(this)).processAsync(inValue);
        }
    }
}
