using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Serialization;
using System.Net;
using System.IO.Compression;

namespace HlidacStatu.Lib.Data.External.DatoveSchranky
{


    public class DSList
    {


        public static IEnumerable<(string ico, string ds, string parentDS, string dsName)> UpdateListDS()
        {
            List<listBox> dsL = new List<listBox>();

            string[] urls = new string[] {
            "https://www.mojedatovaschranka.cz/sds/datafile?format=xml&service=seznam_ds_ovm",
            "https://www.mojedatovaschranka.cz/sds/datafile?format=xml&service=seznam_ds_po",
            "https://www.mojedatovaschranka.cz/sds/datafile?format=xml&service=seznam_ds_pfo",
            "https://www.mojedatovaschranka.cz/sds/datafile?format=xml&service=seznam_ds_fo",
            };

            var serializer = new XmlSerializer(typeof(list), "http://seznam.gov.cz/ovm/datafile/seznam_ds/v1");
            var wc = new System.Net.WebClient();
            foreach (var url in urls)
            {
                wc.Headers[HttpRequestHeader.AcceptEncoding] = "gzip";
                var responseStream = new GZipStream(wc.OpenRead(url), CompressionMode.Decompress);
                var wcreader = new StreamReader(responseStream);
                var xmls = wcreader.ReadToEnd();
                //var xmls = wc.DownloadString(url);
                using (TextReader reader = new StringReader(xmls))
                {
                    var dsFromXML = (list)serializer.Deserialize(reader);
                    if (dsFromXML.box?.Count() > 0)
                    {
                        dsL.AddRange(dsFromXML.box);
                    }

                }
            }

            return dsL.Select(
                m => (m.ico, m.id, m.hierarchy?.masterId, m?.name?.tradeName)
                );

        }






        //------------------------------------------------------------------------------
        //------------------------------------------------------------------------------
        //------------------------------------------------------------------------------




        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by a tool.
        //     Runtime Version:4.0.30319.42000
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------


        // 
        // This source code was auto-generated by xsd, Version=4.8.3928.0.
        // 


        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://seznam.gov.cz/ovm/datafile/seznam_ds/v1")]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://seznam.gov.cz/ovm/datafile/seznam_ds/v1", IsNullable = false)]
        public partial class list
        {

            private listBox[] boxField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("box")]
            public listBox[] box
            {
                get
                {
                    return this.boxField;
                }
                set
                {
                    this.boxField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://seznam.gov.cz/ovm/datafile/seznam_ds/v1")]
        public partial class listBox
        {

            private string idField;

            private string typeField;

            private int subtypeField;

            private bool subtypeFieldSpecified;

            private NameType nameField;

            private string icoField;

            private AddressType addressField;

            private bool pdzField;

            private bool pdzFieldSpecified;

            private bool ovmField;

            private bool ovmFieldSpecified;

            private HierarchyType hierarchyField;

            private string idOVMField;

            /// <remarks/>
            public string id
            {
                get
                {
                    return this.idField;
                }
                set
                {
                    this.idField = value;
                }
            }

            /// <remarks/>
            public string type
            {
                get
                {
                    return this.typeField;
                }
                set
                {
                    this.typeField = value;
                }
            }

            /// <remarks/>
            public int subtype
            {
                get
                {
                    return this.subtypeField;
                }
                set
                {
                    this.subtypeField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool subtypeSpecified
            {
                get
                {
                    return this.subtypeFieldSpecified;
                }
                set
                {
                    this.subtypeFieldSpecified = value;
                }
            }

            /// <remarks/>
            public NameType name
            {
                get
                {
                    return this.nameField;
                }
                set
                {
                    this.nameField = value;
                }
            }

            /// <remarks/>
            public string ico
            {
                get
                {
                    return this.icoField;
                }
                set
                {
                    this.icoField = value;
                }
            }

            /// <remarks/>
            public AddressType address
            {
                get
                {
                    return this.addressField;
                }
                set
                {
                    this.addressField = value;
                }
            }

            /// <remarks/>
            public bool pdz
            {
                get
                {
                    return this.pdzField;
                }
                set
                {
                    this.pdzField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool pdzSpecified
            {
                get
                {
                    return this.pdzFieldSpecified;
                }
                set
                {
                    this.pdzFieldSpecified = value;
                }
            }

            /// <remarks/>
            public bool ovm
            {
                get
                {
                    return this.ovmField;
                }
                set
                {
                    this.ovmField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool ovmSpecified
            {
                get
                {
                    return this.ovmFieldSpecified;
                }
                set
                {
                    this.ovmFieldSpecified = value;
                }
            }

            /// <remarks/>
            public HierarchyType hierarchy
            {
                get
                {
                    return this.hierarchyField;
                }
                set
                {
                    this.hierarchyField = value;
                }
            }

            /// <remarks/>
            public string idOVM
            {
                get
                {
                    return this.idOVMField;
                }
                set
                {
                    this.idOVMField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://seznam.gov.cz/ovm/datafile/seznam_ds/v1")]
        public partial class NameType
        {

            private PersonType personField;

            private string tradeNameField;

            /// <remarks/>
            public PersonType person
            {
                get
                {
                    return this.personField;
                }
                set
                {
                    this.personField = value;
                }
            }

            /// <remarks/>
            public string tradeName
            {
                get
                {
                    return this.tradeNameField;
                }
                set
                {
                    this.tradeNameField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://seznam.gov.cz/ovm/datafile/seznam_ds/v1")]
        public partial class PersonType
        {

            private string firstNameField;

            private string lastNameField;

            private string middleNameField;

            private string lastNameAtBirthField;

            /// <remarks/>
            public string firstName
            {
                get
                {
                    return this.firstNameField;
                }
                set
                {
                    this.firstNameField = value;
                }
            }

            /// <remarks/>
            public string lastName
            {
                get
                {
                    return this.lastNameField;
                }
                set
                {
                    this.lastNameField = value;
                }
            }

            /// <remarks/>
            public string middleName
            {
                get
                {
                    return this.middleNameField;
                }
                set
                {
                    this.middleNameField = value;
                }
            }

            /// <remarks/>
            public string lastNameAtBirth
            {
                get
                {
                    return this.lastNameAtBirthField;
                }
                set
                {
                    this.lastNameAtBirthField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://seznam.gov.cz/ovm/datafile/seznam_ds/v1")]
        public partial class HierarchyType
        {

            private bool isMasterField;

            private string masterIdField;

            /// <remarks/>
            public bool isMaster
            {
                get
                {
                    return this.isMasterField;
                }
                set
                {
                    this.isMasterField = value;
                }
            }

            /// <remarks/>
            public string masterId
            {
                get
                {
                    return this.masterIdField;
                }
                set
                {
                    this.masterIdField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://seznam.gov.cz/ovm/datafile/seznam_ds/v1")]
        public partial class AddressType
        {

            private long codeField;

            private bool codeFieldSpecified;

            private string cityField;

            private string districtField;

            private string streetField;

            private string cpField;

            private string coField;

            private string ceField;

            private string zipField;

            private string regionField;

            private long addressPointField;

            private bool addressPointFieldSpecified;

            private string stateField;

            private string fullAddressField;

            /// <remarks/>
            public long code
            {
                get
                {
                    return this.codeField;
                }
                set
                {
                    this.codeField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool codeSpecified
            {
                get
                {
                    return this.codeFieldSpecified;
                }
                set
                {
                    this.codeFieldSpecified = value;
                }
            }

            /// <remarks/>
            public string city
            {
                get
                {
                    return this.cityField;
                }
                set
                {
                    this.cityField = value;
                }
            }

            /// <remarks/>
            public string district
            {
                get
                {
                    return this.districtField;
                }
                set
                {
                    this.districtField = value;
                }
            }

            /// <remarks/>
            public string street
            {
                get
                {
                    return this.streetField;
                }
                set
                {
                    this.streetField = value;
                }
            }

            /// <remarks/>
            public string cp
            {
                get
                {
                    return this.cpField;
                }
                set
                {
                    this.cpField = value;
                }
            }

            /// <remarks/>
            public string co
            {
                get
                {
                    return this.coField;
                }
                set
                {
                    this.coField = value;
                }
            }

            /// <remarks/>
            public string ce
            {
                get
                {
                    return this.ceField;
                }
                set
                {
                    this.ceField = value;
                }
            }

            /// <remarks/>
            public string zip
            {
                get
                {
                    return this.zipField;
                }
                set
                {
                    this.zipField = value;
                }
            }

            /// <remarks/>
            public string region
            {
                get
                {
                    return this.regionField;
                }
                set
                {
                    this.regionField = value;
                }
            }

            /// <remarks/>
            public long addressPoint
            {
                get
                {
                    return this.addressPointField;
                }
                set
                {
                    this.addressPointField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool addressPointSpecified
            {
                get
                {
                    return this.addressPointFieldSpecified;
                }
                set
                {
                    this.addressPointFieldSpecified = value;
                }
            }

            /// <remarks/>
            public string state
            {
                get
                {
                    return this.stateField;
                }
                set
                {
                    this.stateField = value;
                }
            }

            /// <remarks/>
            public string fullAddress
            {
                get
                {
                    return this.fullAddressField;
                }
                set
                {
                    this.fullAddressField = value;
                }
            }
        }

    }
}