//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class Error : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorDescriptionField;
        
        private System.DateTime dateTimeField;
        
        private string sIDField;
        
        private string requestIDField;
        
        private SRVid sRVidField;
        
        private string vOKOidField;
        
        private string responseLangField;
        
        private string showXSLTpathField;
        
        private string showXSLTtypeField;
        
        private string displayField;
        
        private string descField;
        
        private System.Xml.XmlElement innerExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("ErrorDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
                this.RaisePropertyChanged("DateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SID {
            get {
                return this.sIDField;
            }
            set {
                this.sIDField = value;
                this.RaisePropertyChanged("SID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
                this.RaisePropertyChanged("RequestID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public SRVid SRVid {
            get {
                return this.sRVidField;
            }
            set {
                this.sRVidField = value;
                this.RaisePropertyChanged("SRVid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string vOKOid {
            get {
                return this.vOKOidField;
            }
            set {
                this.vOKOidField = value;
                this.RaisePropertyChanged("vOKOid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ResponseLang {
            get {
                return this.responseLangField;
            }
            set {
                this.responseLangField = value;
                this.RaisePropertyChanged("ResponseLang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ShowXSLTpath {
            get {
                return this.showXSLTpathField;
            }
            set {
                this.showXSLTpathField = value;
                this.RaisePropertyChanged("ShowXSLTpath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ShowXSLTtype {
            get {
                return this.showXSLTtypeField;
            }
            set {
                this.showXSLTtypeField = value;
                this.RaisePropertyChanged("ShowXSLTtype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Display {
            get {
                return this.displayField;
            }
            set {
                this.displayField = value;
                this.RaisePropertyChanged("Display");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("Desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.Xml.XmlElement InnerException {
            get {
                return this.innerExceptionField;
            }
            set {
                this.innerExceptionField = value;
                this.RaisePropertyChanged("InnerException");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class SRVid : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serverIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string serverID {
            get {
                return this.serverIDField;
            }
            set {
                this.serverIDField = value;
                this.RaisePropertyChanged("serverID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RDM_PUB01B")]
    public partial class ArrayOfSubjekt_type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private subjekt_type[] subjektField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subjekt", Order=0)]
        public subjekt_type[] subjekt {
            get {
                return this.subjektField;
            }
            set {
                this.subjektField = value;
                this.RaisePropertyChanged("subjekt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RDM_PUB01B")]
    public partial class subjekt_type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long subjektidField;
        
        private string obchodni_jmenoField;
        
        private string titul_predField;
        
        private string jmenoField;
        
        private string prijmeniField;
        
        private string titul_zaField;
        
        private int rok_narozField;
        
        private bool rok_narozFieldSpecified;
        
        private identifikator_type[] seznam_identifikatoruField;
        
        private adresa_type adresaField;
        
        private oblast_stav_type[] limity_stavField;
        
        private narizeni_stav_type[] limity_stav_narizeniField;
        
        private podpora_type[] seznam_podporField;
        
        private System.DateTime datum_zahajeni_cinnostiField;
        
        private bool datum_zahajeni_cinnostiFieldSpecified;
        
        private ucetni_obdobi[] seznam_uoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long subjektid {
            get {
                return this.subjektidField;
            }
            set {
                this.subjektidField = value;
                this.RaisePropertyChanged("subjektid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string obchodni_jmeno {
            get {
                return this.obchodni_jmenoField;
            }
            set {
                this.obchodni_jmenoField = value;
                this.RaisePropertyChanged("obchodni_jmeno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string titul_pred {
            get {
                return this.titul_predField;
            }
            set {
                this.titul_predField = value;
                this.RaisePropertyChanged("titul_pred");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string jmeno {
            get {
                return this.jmenoField;
            }
            set {
                this.jmenoField = value;
                this.RaisePropertyChanged("jmeno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string prijmeni {
            get {
                return this.prijmeniField;
            }
            set {
                this.prijmeniField = value;
                this.RaisePropertyChanged("prijmeni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string titul_za {
            get {
                return this.titul_zaField;
            }
            set {
                this.titul_zaField = value;
                this.RaisePropertyChanged("titul_za");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int rok_naroz {
            get {
                return this.rok_narozField;
            }
            set {
                this.rok_narozField = value;
                this.RaisePropertyChanged("rok_naroz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rok_narozSpecified {
            get {
                return this.rok_narozFieldSpecified;
            }
            set {
                this.rok_narozFieldSpecified = value;
                this.RaisePropertyChanged("rok_narozSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("identifikator", IsNullable=false)]
        public identifikator_type[] seznam_identifikatoru {
            get {
                return this.seznam_identifikatoruField;
            }
            set {
                this.seznam_identifikatoruField = value;
                this.RaisePropertyChanged("seznam_identifikatoru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public adresa_type adresa {
            get {
                return this.adresaField;
            }
            set {
                this.adresaField = value;
                this.RaisePropertyChanged("adresa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("oblast_stav", IsNullable=false)]
        public oblast_stav_type[] limity_stav {
            get {
                return this.limity_stavField;
            }
            set {
                this.limity_stavField = value;
                this.RaisePropertyChanged("limity_stav");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("narizeni_stav", IsNullable=false)]
        public narizeni_stav_type[] limity_stav_narizeni {
            get {
                return this.limity_stav_narizeniField;
            }
            set {
                this.limity_stav_narizeniField = value;
                this.RaisePropertyChanged("limity_stav_narizeni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("podpora", IsNullable=false)]
        public podpora_type[] seznam_podpor {
            get {
                return this.seznam_podporField;
            }
            set {
                this.seznam_podporField = value;
                this.RaisePropertyChanged("seznam_podpor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=12)]
        public System.DateTime datum_zahajeni_cinnosti {
            get {
                return this.datum_zahajeni_cinnostiField;
            }
            set {
                this.datum_zahajeni_cinnostiField = value;
                this.RaisePropertyChanged("datum_zahajeni_cinnosti");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datum_zahajeni_cinnostiSpecified {
            get {
                return this.datum_zahajeni_cinnostiFieldSpecified;
            }
            set {
                this.datum_zahajeni_cinnostiFieldSpecified = value;
                this.RaisePropertyChanged("datum_zahajeni_cinnostiSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=13)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ucetni_obdobi[] seznam_uo {
            get {
                return this.seznam_uoField;
            }
            set {
                this.seznam_uoField = value;
                this.RaisePropertyChanged("seznam_uo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RDM_PUB01B")]
    public partial class identifikator_type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime platnost_doField;
        
        private bool platnost_doFieldSpecified;
        
        private System.DateTime platnost_odField;
        
        private bool platnost_odFieldSpecified;
        
        private string typField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime platnost_do {
            get {
                return this.platnost_doField;
            }
            set {
                this.platnost_doField = value;
                this.RaisePropertyChanged("platnost_do");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool platnost_doSpecified {
            get {
                return this.platnost_doFieldSpecified;
            }
            set {
                this.platnost_doFieldSpecified = value;
                this.RaisePropertyChanged("platnost_doSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime platnost_od {
            get {
                return this.platnost_odField;
            }
            set {
                this.platnost_odField = value;
                this.RaisePropertyChanged("platnost_od");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool platnost_odSpecified {
            get {
                return this.platnost_odFieldSpecified;
            }
            set {
                this.platnost_odFieldSpecified = value;
                this.RaisePropertyChanged("platnost_odSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string typ {
            get {
                return this.typField;
            }
            set {
                this.typField = value;
                this.RaisePropertyChanged("typ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RDM_PUB01B")]
    public partial class adresa_type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ulicenazField;
        
        private string cisdomhodField;
        
        private string cisorhodField;
        
        private string cisorpisField;
        
        private string cobcenazField;
        
        private string mcastnazField;
        
        private string obecnazField;
        
        private string pscField;
        
        private string adrline1Field;
        
        private string adrline2Field;
        
        private string adrline3Field;
        
        private string adrline4Field;
        
        private string adrpostcodeField;
        
        private int kodField;
        
        private bool kodFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ulicenaz {
            get {
                return this.ulicenazField;
            }
            set {
                this.ulicenazField = value;
                this.RaisePropertyChanged("ulicenaz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cisdomhod {
            get {
                return this.cisdomhodField;
            }
            set {
                this.cisdomhodField = value;
                this.RaisePropertyChanged("cisdomhod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string cisorhod {
            get {
                return this.cisorhodField;
            }
            set {
                this.cisorhodField = value;
                this.RaisePropertyChanged("cisorhod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string cisorpis {
            get {
                return this.cisorpisField;
            }
            set {
                this.cisorpisField = value;
                this.RaisePropertyChanged("cisorpis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string cobcenaz {
            get {
                return this.cobcenazField;
            }
            set {
                this.cobcenazField = value;
                this.RaisePropertyChanged("cobcenaz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string mcastnaz {
            get {
                return this.mcastnazField;
            }
            set {
                this.mcastnazField = value;
                this.RaisePropertyChanged("mcastnaz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string obecnaz {
            get {
                return this.obecnazField;
            }
            set {
                this.obecnazField = value;
                this.RaisePropertyChanged("obecnaz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string psc {
            get {
                return this.pscField;
            }
            set {
                this.pscField = value;
                this.RaisePropertyChanged("psc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string adrline1 {
            get {
                return this.adrline1Field;
            }
            set {
                this.adrline1Field = value;
                this.RaisePropertyChanged("adrline1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string adrline2 {
            get {
                return this.adrline2Field;
            }
            set {
                this.adrline2Field = value;
                this.RaisePropertyChanged("adrline2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string adrline3 {
            get {
                return this.adrline3Field;
            }
            set {
                this.adrline3Field = value;
                this.RaisePropertyChanged("adrline3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string adrline4 {
            get {
                return this.adrline4Field;
            }
            set {
                this.adrline4Field = value;
                this.RaisePropertyChanged("adrline4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string adrpostcode {
            get {
                return this.adrpostcodeField;
            }
            set {
                this.adrpostcodeField = value;
                this.RaisePropertyChanged("adrpostcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int kod {
            get {
                return this.kodField;
            }
            set {
                this.kodField = value;
                this.RaisePropertyChanged("kod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool kodSpecified {
            get {
                return this.kodFieldSpecified;
            }
            set {
                this.kodFieldSpecified = value;
                this.RaisePropertyChanged("kodSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RDM_PUB01B")]
    public partial class oblast_stav_type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime platnostField;
        
        private string oblast_kodField;
        
        private double limitField;
        
        private double cerpanoField;
        
        private bool cerpanoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime platnost {
            get {
                return this.platnostField;
            }
            set {
                this.platnostField = value;
                this.RaisePropertyChanged("platnost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string oblast_kod {
            get {
                return this.oblast_kodField;
            }
            set {
                this.oblast_kodField = value;
                this.RaisePropertyChanged("oblast_kod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
                this.RaisePropertyChanged("limit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double cerpano {
            get {
                return this.cerpanoField;
            }
            set {
                this.cerpanoField = value;
                this.RaisePropertyChanged("cerpano");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cerpanoSpecified {
            get {
                return this.cerpanoFieldSpecified;
            }
            set {
                this.cerpanoFieldSpecified = value;
                this.RaisePropertyChanged("cerpanoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RDM_PUB01B")]
    public partial class narizeni_stav_type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime platnostField;
        
        private string kodField;
        
        private double limitField;
        
        private double cerpanoField;
        
        private bool cerpanoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime platnost {
            get {
                return this.platnostField;
            }
            set {
                this.platnostField = value;
                this.RaisePropertyChanged("platnost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string kod {
            get {
                return this.kodField;
            }
            set {
                this.kodField = value;
                this.RaisePropertyChanged("kod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
                this.RaisePropertyChanged("limit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double cerpano {
            get {
                return this.cerpanoField;
            }
            set {
                this.cerpanoField = value;
                this.RaisePropertyChanged("cerpano");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cerpanoSpecified {
            get {
                return this.cerpanoFieldSpecified;
            }
            set {
                this.cerpanoFieldSpecified = value;
                this.RaisePropertyChanged("cerpanoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RDM_PUB01B")]
    public partial class podpora_type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private podpora_oblast_enum oblastField;
        
        private System.DateTime datum_prideleniField;
        
        private mena_enum menaField;
        
        private double castka_kcField;
        
        private bool castka_kcFieldSpecified;
        
        private double castka_euroField;
        
        private bool castka_euroFieldSpecified;
        
        private int forma_podporyField;
        
        private string ucel_podporyField;
        
        private int pravni_akt_poskytnutiField;
        
        private string cj_poskytovatelField;
        
        private string cj_prijemceField;
        
        private rezim_podpory_type rezim_podporyField;
        
        private int id_podporyField;
        
        private long poskytovatel_idField;
        
        private string poskytovatel_ojmField;
        
        private string poskytovatel_icField;
        
        private int stavField;
        
        private priznak[] seznam_priznakyField;
        
        private System.DateTime insdatField;
        
        private System.DateTime edidatField;
        
        private bool edidatFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public podpora_oblast_enum oblast {
            get {
                return this.oblastField;
            }
            set {
                this.oblastField = value;
                this.RaisePropertyChanged("oblast");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime datum_prideleni {
            get {
                return this.datum_prideleniField;
            }
            set {
                this.datum_prideleniField = value;
                this.RaisePropertyChanged("datum_prideleni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public mena_enum mena {
            get {
                return this.menaField;
            }
            set {
                this.menaField = value;
                this.RaisePropertyChanged("mena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double castka_kc {
            get {
                return this.castka_kcField;
            }
            set {
                this.castka_kcField = value;
                this.RaisePropertyChanged("castka_kc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool castka_kcSpecified {
            get {
                return this.castka_kcFieldSpecified;
            }
            set {
                this.castka_kcFieldSpecified = value;
                this.RaisePropertyChanged("castka_kcSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double castka_euro {
            get {
                return this.castka_euroField;
            }
            set {
                this.castka_euroField = value;
                this.RaisePropertyChanged("castka_euro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool castka_euroSpecified {
            get {
                return this.castka_euroFieldSpecified;
            }
            set {
                this.castka_euroFieldSpecified = value;
                this.RaisePropertyChanged("castka_euroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int forma_podpory {
            get {
                return this.forma_podporyField;
            }
            set {
                this.forma_podporyField = value;
                this.RaisePropertyChanged("forma_podpory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ucel_podpory {
            get {
                return this.ucel_podporyField;
            }
            set {
                this.ucel_podporyField = value;
                this.RaisePropertyChanged("ucel_podpory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int pravni_akt_poskytnuti {
            get {
                return this.pravni_akt_poskytnutiField;
            }
            set {
                this.pravni_akt_poskytnutiField = value;
                this.RaisePropertyChanged("pravni_akt_poskytnuti");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string cj_poskytovatel {
            get {
                return this.cj_poskytovatelField;
            }
            set {
                this.cj_poskytovatelField = value;
                this.RaisePropertyChanged("cj_poskytovatel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string cj_prijemce {
            get {
                return this.cj_prijemceField;
            }
            set {
                this.cj_prijemceField = value;
                this.RaisePropertyChanged("cj_prijemce");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public rezim_podpory_type rezim_podpory {
            get {
                return this.rezim_podporyField;
            }
            set {
                this.rezim_podporyField = value;
                this.RaisePropertyChanged("rezim_podpory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int id_podpory {
            get {
                return this.id_podporyField;
            }
            set {
                this.id_podporyField = value;
                this.RaisePropertyChanged("id_podpory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public long poskytovatel_id {
            get {
                return this.poskytovatel_idField;
            }
            set {
                this.poskytovatel_idField = value;
                this.RaisePropertyChanged("poskytovatel_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string poskytovatel_ojm {
            get {
                return this.poskytovatel_ojmField;
            }
            set {
                this.poskytovatel_ojmField = value;
                this.RaisePropertyChanged("poskytovatel_ojm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string poskytovatel_ic {
            get {
                return this.poskytovatel_icField;
            }
            set {
                this.poskytovatel_icField = value;
                this.RaisePropertyChanged("poskytovatel_ic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int stav {
            get {
                return this.stavField;
            }
            set {
                this.stavField = value;
                this.RaisePropertyChanged("stav");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=16)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public priznak[] seznam_priznaky {
            get {
                return this.seznam_priznakyField;
            }
            set {
                this.seznam_priznakyField = value;
                this.RaisePropertyChanged("seznam_priznaky");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=17)]
        public System.DateTime insdat {
            get {
                return this.insdatField;
            }
            set {
                this.insdatField = value;
                this.RaisePropertyChanged("insdat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=18)]
        public System.DateTime edidat {
            get {
                return this.edidatField;
            }
            set {
                this.edidatField = value;
                this.RaisePropertyChanged("edidat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool edidatSpecified {
            get {
                return this.edidatFieldSpecified;
            }
            set {
                this.edidatFieldSpecified = value;
                this.RaisePropertyChanged("edidatSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RDM_PUB01B")]
    public enum podpora_oblast_enum {
        
        /// <remarks/>
        ZP,
        
        /// <remarks/>
        RY,
        
        /// <remarks/>
        DO,
        
        /// <remarks/>
        OS,
        
        /// <remarks/>
        SL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RDM_PUB01B")]
    public enum mena_enum {
        
        /// <remarks/>
        CZK,
        
        /// <remarks/>
        EUR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RDM_PUB01B")]
    public partial class rezim_podpory_type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool adhocField;
        
        private string nazevField;
        
        private System.DateTime datum_odField;
        
        private bool datum_odFieldSpecified;
        
        private System.DateTime datum_doField;
        
        private bool datum_doFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool adhoc {
            get {
                return this.adhocField;
            }
            set {
                this.adhocField = value;
                this.RaisePropertyChanged("adhoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string nazev {
            get {
                return this.nazevField;
            }
            set {
                this.nazevField = value;
                this.RaisePropertyChanged("nazev");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime datum_od {
            get {
                return this.datum_odField;
            }
            set {
                this.datum_odField = value;
                this.RaisePropertyChanged("datum_od");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datum_odSpecified {
            get {
                return this.datum_odFieldSpecified;
            }
            set {
                this.datum_odFieldSpecified = value;
                this.RaisePropertyChanged("datum_odSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime datum_do {
            get {
                return this.datum_doField;
            }
            set {
                this.datum_doField = value;
                this.RaisePropertyChanged("datum_do");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datum_doSpecified {
            get {
                return this.datum_doFieldSpecified;
            }
            set {
                this.datum_doFieldSpecified = value;
                this.RaisePropertyChanged("datum_doSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RDM_PUB01B")]
    public partial class priznak : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int kodField;
        
        private string nazevField;
        
        private string popisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int kod {
            get {
                return this.kodField;
            }
            set {
                this.kodField = value;
                this.RaisePropertyChanged("kod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string nazev {
            get {
                return this.nazevField;
            }
            set {
                this.nazevField = value;
                this.RaisePropertyChanged("nazev");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string popis {
            get {
                return this.popisField;
            }
            set {
                this.popisField = value;
                this.RaisePropertyChanged("popis");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RDM_PUB01B")]
    public partial class ucetni_obdobi : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime datum_doField;
        
        private System.DateTime datum_odField;
        
        private int id_uoField;
        
        private bool id_uoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime datum_do {
            get {
                return this.datum_doField;
            }
            set {
                this.datum_doField = value;
                this.RaisePropertyChanged("datum_do");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime datum_od {
            get {
                return this.datum_odField;
            }
            set {
                this.datum_odField = value;
                this.RaisePropertyChanged("datum_od");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int id_uo {
            get {
                return this.id_uoField;
            }
            set {
                this.id_uoField = value;
                this.RaisePropertyChanged("id_uo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_uoSpecified {
            get {
                return this.id_uoFieldSpecified;
            }
            set {
                this.id_uoFieldSpecified = value;
                this.RaisePropertyChanged("id_uoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RDM_PUB01B")]
    public partial class ArrayOfSubjektId_type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long[] subjektidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subjektid", Order=0)]
        public long[] subjektid {
            get {
                return this.subjektidField;
            }
            set {
                this.subjektidField = value;
                this.RaisePropertyChanged("subjektid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RDM_PUB_Response))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RDM_PUB01B")]
    public partial class RDM_PUB_Response_base_type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int pocetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int pocet {
            get {
                return this.pocetField;
            }
            set {
                this.pocetField = value;
                this.RaisePropertyChanged("pocet");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RDM_PUB01B")]
    public partial class RDM_PUB_Response : RDM_PUB_Response_base_type {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("seznam_subjektid", typeof(ArrayOfSubjektId_type), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("seznam_subjektu", typeof(ArrayOfSubjekt_type), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class ResponseHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
                this.RaisePropertyChanged("RequestID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SRVid sRVidField;
        
        private TimeStamp timeStampField;
        
        private ResponseHeader responseHeaderField;
        
        private ResponseResponseContent responseContentField;
        
        private string vOKOidField;
        
        private string sIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SRVid SRVid {
            get {
                return this.sRVidField;
            }
            set {
                this.sRVidField = value;
                this.RaisePropertyChanged("SRVid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TimeStamp TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ResponseHeader ResponseHeader {
            get {
                return this.responseHeaderField;
            }
            set {
                this.responseHeaderField = value;
                this.RaisePropertyChanged("ResponseHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ResponseResponseContent ResponseContent {
            get {
                return this.responseContentField;
            }
            set {
                this.responseContentField = value;
                this.RaisePropertyChanged("ResponseContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string vOKOid {
            get {
                return this.vOKOidField;
            }
            set {
                this.vOKOidField = value;
                this.RaisePropertyChanged("vOKOid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SID {
            get {
                return this.sIDField;
            }
            set {
                this.sIDField = value;
                this.RaisePropertyChanged("SID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class TimeStamp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TimeStampType typeField;
        
        private System.DateTime valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TimeStampType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public System.DateTime Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.pds.eu/vOKO/v0200")]
    public enum TimeStampType {
        
        /// <remarks/>
        @base,
        
        /// <remarks/>
        qualified,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class ResponseResponseContent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RDM_PUB_Response itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Response", Namespace="http://www.pds.eu/RDM_PUB01B", Order=0)]
        public RDM_PUB_Response Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RDM_PUB01B")]
    public partial class dotaz_zmeny_type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long subjektidField;
        
        private bool subjektidFieldSpecified;
        
        private string poskytovatelField;
        
        private System.DateTime zmeny_odField;
        
        private System.DateTime zmeny_doField;
        
        private bool zmeny_doFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long subjektid {
            get {
                return this.subjektidField;
            }
            set {
                this.subjektidField = value;
                this.RaisePropertyChanged("subjektid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subjektidSpecified {
            get {
                return this.subjektidFieldSpecified;
            }
            set {
                this.subjektidFieldSpecified = value;
                this.RaisePropertyChanged("subjektidSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string poskytovatel {
            get {
                return this.poskytovatelField;
            }
            set {
                this.poskytovatelField = value;
                this.RaisePropertyChanged("poskytovatel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime zmeny_od {
            get {
                return this.zmeny_odField;
            }
            set {
                this.zmeny_odField = value;
                this.RaisePropertyChanged("zmeny_od");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime zmeny_do {
            get {
                return this.zmeny_doField;
            }
            set {
                this.zmeny_doField = value;
                this.RaisePropertyChanged("zmeny_do");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zmeny_doSpecified {
            get {
                return this.zmeny_doFieldSpecified;
            }
            set {
                this.zmeny_doFieldSpecified = value;
                this.RaisePropertyChanged("zmeny_doSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RDM_PUB01B")]
    public partial class dotaz_subjektid_type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long subjektidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long subjektid {
            get {
                return this.subjektidField;
            }
            set {
                this.subjektidField = value;
                this.RaisePropertyChanged("subjektid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(dotaz_psc_type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(dotaz_obec_type))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RDM_PUB01B")]
    public partial class dotaz_jmeno_prijmeni_type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string jmenoField;
        
        private string prijmeniField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string jmeno {
            get {
                return this.jmenoField;
            }
            set {
                this.jmenoField = value;
                this.RaisePropertyChanged("jmeno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string prijmeni {
            get {
                return this.prijmeniField;
            }
            set {
                this.prijmeniField = value;
                this.RaisePropertyChanged("prijmeni");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RDM_PUB01B")]
    public partial class dotaz_psc_type : dotaz_jmeno_prijmeni_type {
        
        private string pscField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string psc {
            get {
                return this.pscField;
            }
            set {
                this.pscField = value;
                this.RaisePropertyChanged("psc");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RDM_PUB01B")]
    public partial class dotaz_obec_type : dotaz_jmeno_prijmeni_type {
        
        private string obecnazField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string obecnaz {
            get {
                return this.obecnazField;
            }
            set {
                this.obecnazField = value;
                this.RaisePropertyChanged("obecnaz");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RDM_PUB01B")]
    public partial class dotaz_ic_type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string icField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ic {
            get {
                return this.icField;
            }
            set {
                this.icField = value;
                this.RaisePropertyChanged("ic");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RDM_PUB01B")]
    public partial class dotaz_detail_choice_type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dotaz_ic", typeof(dotaz_ic_type), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("dotaz_obec_type", typeof(dotaz_obec_type), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("dotaz_psc", typeof(dotaz_psc_type), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("dotaz_subjektid", typeof(dotaz_subjektid_type), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/RDM_PUB01B")]
    public partial class RDM_PUB_Request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dotaz_detail", typeof(dotaz_detail_choice_type), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("dotaz_zmeny", typeof(dotaz_zmeny_type), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class RequestHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestIDField;
        
        private RequestHeaderSubject subjectField;
        
        private RequestHeaderRequestType requestTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
                this.RaisePropertyChanged("RequestID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RequestHeaderSubject Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("Subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RequestHeaderRequestType RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
                this.RaisePropertyChanged("RequestType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class RequestHeaderSubject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string subjectIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string subjectID {
            get {
                return this.subjectIDField;
            }
            set {
                this.subjectIDField = value;
                this.RaisePropertyChanged("subjectID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class RequestHeaderRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class AppInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AppInfoAppModule appModuleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AppInfoAppModule AppModule {
            get {
                return this.appModuleField;
            }
            set {
                this.appModuleField = value;
                this.RaisePropertyChanged("AppModule");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class AppInfoAppModule : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class UIDkey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dnField;
        
        private string addressADField;
        
        private string certificateSNField;
        
        private string certificateOwnerField;
        
        private string certificateOrganizationField;
        
        private string certificateIssuerField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dn {
            get {
                return this.dnField;
            }
            set {
                this.dnField = value;
                this.RaisePropertyChanged("dn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string addressAD {
            get {
                return this.addressADField;
            }
            set {
                this.addressADField = value;
                this.RaisePropertyChanged("addressAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string certificateSN {
            get {
                return this.certificateSNField;
            }
            set {
                this.certificateSNField = value;
                this.RaisePropertyChanged("certificateSN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string certificateOwner {
            get {
                return this.certificateOwnerField;
            }
            set {
                this.certificateOwnerField = value;
                this.RaisePropertyChanged("certificateOwner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string certificateOrganization {
            get {
                return this.certificateOrganizationField;
            }
            set {
                this.certificateOrganizationField = value;
                this.RaisePropertyChanged("certificateOrganization");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string certificateIssuer {
            get {
                return this.certificateIssuerField;
            }
            set {
                this.certificateIssuerField = value;
                this.RaisePropertyChanged("certificateIssuer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class Request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private UIDkey uIDkeyField;
        
        private TimeStamp timeStampField;
        
        private AppInfo appInfoField;
        
        private RequestHeader requestHeaderField;
        
        private RequestRequestContent requestContentField;
        
        private string vOKOidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public UIDkey UIDkey {
            get {
                return this.uIDkeyField;
            }
            set {
                this.uIDkeyField = value;
                this.RaisePropertyChanged("UIDkey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TimeStamp TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public AppInfo AppInfo {
            get {
                return this.appInfoField;
            }
            set {
                this.appInfoField = value;
                this.RaisePropertyChanged("AppInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public RequestHeader RequestHeader {
            get {
                return this.requestHeaderField;
            }
            set {
                this.requestHeaderField = value;
                this.RaisePropertyChanged("RequestHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public RequestRequestContent RequestContent {
            get {
                return this.requestContentField;
            }
            set {
                this.requestContentField = value;
                this.RaisePropertyChanged("RequestContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string vOKOid {
            get {
                return this.vOKOidField;
            }
            set {
                this.vOKOidField = value;
                this.RaisePropertyChanged("vOKOid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.pds.eu/vOKO/v0200")]
    public partial class RequestRequestContent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RDM_PUB_Request itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Request", Namespace="http://www.pds.eu/RDM_PUB01B", Order=0)]
        public RDM_PUB_Request Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.pds.eu/vOKO/v0200", ConfigurationName="eAgri.DeMinimis.WS.RDM_PUB01B")]
    public interface RDM_PUB01B {
        
        // CODEGEN: Generating message contract since the operation process is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="process", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.Error), Action="process", Name="Error")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RDM_PUB_Response_base_type))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(dotaz_jmeno_prijmeni_type))]
        HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.processResponse process(HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.processRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="process", ReplyAction="*")]
        System.Threading.Tasks.Task<HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.processResponse> processAsync(HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.processRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.pds.eu/vOKO/v0200", Order=0)]
        public HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.Request Request;
        
        public processRequest() {
        }
        
        public processRequest(HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.Request Request) {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.pds.eu/vOKO/v0200", Order=0)]
        public HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.Response Response;
        
        public processResponse() {
        }
        
        public processResponse(HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.Response Response) {
            this.Response = Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RDM_PUB01BChannel : HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.RDM_PUB01B, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RDM_PUB01BClient : System.ServiceModel.ClientBase<HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.RDM_PUB01B>, HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.RDM_PUB01B {
        
        public RDM_PUB01BClient() {
        }
        
        public RDM_PUB01BClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RDM_PUB01BClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RDM_PUB01BClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RDM_PUB01BClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.processResponse HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.RDM_PUB01B.process(HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.processRequest request) {
            return base.Channel.process(request);
        }
        
        public HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.Response process(HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.Request Request) {
            HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.processRequest inValue = new HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.processRequest();
            inValue.Request = Request;
            HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.processResponse retVal = ((HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.RDM_PUB01B)(this)).process(inValue);
            return retVal.Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.processResponse> HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.RDM_PUB01B.processAsync(HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.processRequest request) {
            return base.Channel.processAsync(request);
        }
        
        public System.Threading.Tasks.Task<HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.processResponse> processAsync(HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.Request Request) {
            HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.processRequest inValue = new HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.processRequest();
            inValue.Request = Request;
            return ((HlidacStatu.Lib.Data.External.eAgri.DeMinimis.WS.RDM_PUB01B)(this)).processAsync(inValue);
        }
    }
}
